name: SneakyResourcePacks
version: "1.0"
main: com.danidipp.sneakyresourcepacks.SneakyResourcePacks
api-version: "1.20"
authors:
  - DaniDipp
description: "Paper plugin for managing multiple server resourcepacks"
dependencies:
  server:
    SneakyCharacterManager:
      load: BEFORE
      required: false